// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Name      string           `json:"name"`
	Descr     string           `json:"descr"`
}

type Entry struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Pubic     pgtype.Bool      `json:"pubic"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Title     string           `json:"title"`
	Descr     string           `json:"descr"`
	Signature string           `json:"signature"`
}

type EntryCategory struct {
	UserID     int32 `json:"user_id"`
	EntryID    int32 `json:"entry_id"`
	CategoryID int32 `json:"category_id"`
}

type User struct {
	ID        int32            `json:"id"`
	Uid       pgtype.UUID      `json:"uid"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	RealName  string           `json:"real_name"`
	Username  string           `json:"username"`
	Hash      string           `json:"hash"`
	Email     string           `json:"email"`
	Pubkey    []byte           `json:"pubkey"`
}
